default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: computer_simulator_development

test:
  <<: *default
  database: computer_simulator_test

production:
  <<: *default
  database: computer_simulator
